export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FETCH_SPECIFIC_SLUG_MASTER = 'FETCH_SPECIFIC_SLUG_MASTER';
export const UPDATE_SLUG = 'UPDATE_SLUG';